language: node_js
sudo: false
node_js:
  - "5.5.0"

before_script:
  - apt-get install ttf-nepali-fonts
  - npm install

script:
  - npm test
  - node_modules/imgur/cli.js ./data/*

cache:
  directories:
    - node_modules
